name: nuclear-norm-thesis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - tqdm
      - opencv-python
